In [69]:
import pandas as pd
import numpy as np

In [114]:
#Importando todos los datasets indidivuales por sentimiento
df_pred_anger = pd.read_csv('predictions/pred_anger.csv')
df_pred_anticipation = pd.read_csv('predictions/pred_anticipation.csv')
df_pred_disgust = pd.read_csv('predictions/pred_disgust.csv')
df_pred_fear = pd.read_csv('predictions/pred_fear.csv')
df_pred_joy = pd.read_csv('predictions/pred_joy.csv')
df_pred_love = pd.read_csv('predictions/pred_love.csv')
df_pred_optimism = pd.read_csv('predictions/pred_optimism.csv')
df_pred_pessimism = pd.read_csv('predictions/pred_pessimism.csv')
df_pred_sadness = pd.read_csv('predictions/pred_sadness.csv')
df_pred_surprise = pd.read_csv('predictions/pred_surprise.csv')
df_pred_trust = pd.read_csv('predictions/pred_trust.csv')

In [115]:
df_pred_anger.head()

              ID     anger
0  2018-Es-06697  0.421123
1  2018-Es-05385  0.038619
2  2018-Es-03777  0.000790
3  2018-Es-02175  0.000025
4  2018-Es-00726  0.841254

In [116]:
df_pred_surprise.head()

              ID  surprise
0  2018-Es-06697  0.002313
1  2018-Es-05385  0.000022
2  2018-Es-03777  0.000033
3  2018-Es-02175  0.000009
4  2018-Es-00726  0.000030

# Juntando todos los dataset

In [117]:
df_all = df_pred_anger
df_all['anticipation'] = df_pred_anticipation.anticipation
df_all['disgust'] = df_pred_disgust.disgust
df_all['fear'] = df_pred_fear.fear
df_all['joy'] = df_pred_joy.joy
df_all['love'] = df_pred_love.love
df_all['optimism'] = df_pred_optimism.optimism
df_all['pessimism'] = df_pred_pessimism.pessimism
df_all['sadness'] = df_pred_sadness.sadness
df_all['surprise'] = df_pred_surprise.surprise
df_all['trust'] = df_pred_trust.trust

In [118]:
df_all.head()

,ID,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-06697,0.421123,0.995942,0.000546,1.498124e-03,0.000002,0.000002,1.538391e-06,0.259505,0.000001,0.002313,0.000111
1,2018-Es-05385,0.038619,0.920777,0.000012,4.928950e-02,0.689762,0.000008,3.068997e-06,0.916841,0.000470,0.000022,0.367165
2,2018-Es-03777,0.000790,0.000264,0.018703,6.846598e-08,0.000028,0.000007,2.251514e-04,0.000124,0.000002,0.000033,0.000181
3,2018-Es-02175,0.000025,0.004439,0.000336,2.458723e-04,0.986098,0.035020,4.995558e-03,0.000037,0.000027,0.000009,0.001155
4,2018-Es-00726,0.841254,0.324312,0.176007,3.021254e-02,0.000032,0.000143,4.600923e-07,0.179304,0.939739,0.000030,0.000160

In [119]:
#Filtramos sentimientos con un valor pivote y cambiamos el valor a boolean
FILTER_SENTIMENT = 0.75
df_all.anger = [True if x>FILTER_SENTIMENT else False for x in df_all.anger]
df_all.anticipation = [True if x>FILTER_SENTIMENT else False for x in df_all.anticipation]
df_all.disgust = [True if x>FILTER_SENTIMENT else False for x in df_all.disgust]
df_all.fear = [True if x>FILTER_SENTIMENT else False for x in df_all.fear]
df_all.joy = [True if x>FILTER_SENTIMENT else False for x in df_all.joy]
df_all.love = [True if x>FILTER_SENTIMENT else False for x in df_all.love]
df_all.optimism = [True if x>FILTER_SENTIMENT else False for x in df_all.optimism]
df_all.pessimism = [True if x>FILTER_SENTIMENT else False for x in df_all.pessimism]
df_all.sadness = [True if x>FILTER_SENTIMENT else False for x in df_all.sadness]
df_all.surprise = [True if x>FILTER_SENTIMENT else False for x in df_all.surprise]
df_all.trust = [True if x>FILTER_SENTIMENT else False for x in df_all.trust]

In [121]:
df_all.head()

,ID,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-06697,False,True,False,False,False,False,False,False,False,False,False
1,2018-Es-05385,False,True,False,False,False,False,False,True,False,False,False
2,2018-Es-03777,False,False,False,False,False,False,False,False,False,False,False
3,2018-Es-02175,False,False,False,False,True,False,False,False,False,False,False
4,2018-Es-00726,True,False,False,False,False,False,False,False,True,False,False

In [123]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 679 entries, 0 to 678
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            679 non-null    object
 1   anger         679 non-null    bool
 2   anticipation  679 non-null    bool
 3   disgust       679 non-null    bool
 4   fear          679 non-null    bool
 5   joy           679 non-null    bool
 6   love          679 non-null    bool
 7   optimism      679 non-null    bool
 8   pessimism     679 non-null    bool
 9   sadness       679 non-null    bool
 10  surprise      679 non-null    bool
 11  trust         679 non-null    bool
dtypes: bool(11), object(1)
memory usage: 12.7+ KB

In [ ]:
df_all